=== dogi-zz/FilmTool/src/assets/index.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": ["name", "columns"],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "toStringExpression": {
      "type": "string"
    },
    "showOnHome": {
      "type": "boolean"
    },
    "columns": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "oneOf": [
            {
              "required": ["type", "name", "displayName"],
              "additionalProperties": false,
              "properties": {
                "type": {
                  "type": "string",
                  "enum": ["string", "number"]
                },
                "name": {
                  "type": "string"
                },
                "displayName": {
                  "type": "string"
                }
              }
            },
            {
              "required": ["type", "name", "displayName", "options"],
              "additionalProperties": false,
              "properties": {
                "type": {
                  "const": "select"
                },
                "name": {
                  "type": "string"
                },
                "displayName": {
                  "type": "string"
                },
                "options": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        }
      ]
    },
    "infoQueries": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "query"],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "query": {
            "type": "object",
            "required": ["select", "from", "where"],
            "properties": {
              "select": {
                "type": "array",
                "items": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "from": {
                "type": "string"
              },
              "where": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }

            }
          }
        }
      }
    }
  }
}

=== dogi-zz/FilmTool/src/assets/table.film.json
{
  "name": "Filme",
  "showOnHome": true,
  "columns": [
    { "type": "number", "name": "id", "displayName": "ID" },
    { "type": "string", "name": "title", "displayName": "Titel" },
    { "type": "string", "name": "subtitle", "displayName": "Untertitel" },
    { "type": "number", "name": "jahr", "displayName": "Erscheinungsjahr" },
    { "type": "select", "name": "genre", "displayName": "Genre", "options": ["Doku", "Abenteuer", "Liebesfilm"]},
    { "type": "relation", "name": "regie", "displayName": "Regie", "table": "person" }
  ],
  "infoQueries": [
    {
      "name": "Alle Filme vom selben Regisseur",
      "query": {
        "select": [["f.name", "Film"], ["f.jahr", "Jahr"]],
        "from": "film f",
        "where": ["f.regie = {regie}"],
        "oder": ["f.jahr ASC"]
      }
    }
  ]
}

=== dogi-zz/FilmTool/src/assets/table.person.json
{
  "name": "Person",
  "showOnHome": true,
  "columns": [
    { "type": "number", "name": "id", "displayName": "ID" },
    { "type": "string", "name": "name1", "displayName": "Vorname" },
    { "type": "string", "name": "name2", "displayName": "Nachname" },
    { "type": "relation", "name": "role", "displayName": "Rolle", "table": "person_role" },
    { "type": "select", "name": "sex", "displayName": "Geschlecht", "options": ["Mann", "Frau"]},
    { "type": "select", "name": "nice", "displayName": "Nett oder Böse", "options": ["nett", "böse"]}
  ],
  "infoQueries": [
    {
      "name": "Alle Filme mit der Person",
      "query": {
        "select": [["f.name", "Film"], ["r.rolle", "Rolle"]],
        "from": "person p JOIN rolle r on p.rolle = r.id JOIN film.f on r.film = f.id",
        "where": ["p.id = {id}"]
      }
    },
    {
      "name": "Alle Freunde Person",
      "query": {
        "select": [["p.name", "Freund"]],
        "from": "person p1 JOIN person p2 on p2.id = p1.freund",
        "where": ["p1.id = {id}"]
      }
    }

  ]
}

=== dogi-zz/FilmTool/src/assets/table.filmtesttest.json
{
    "name": "Filme",
    "showOnHome": true,
    "columns": [
      { "type": "number", "name": "FilmID", "displayName": "Film ID" },
      { "type": "text", "name": "Titel", "displayName": "Filmtitel" },
      { "type": "date", "name": "BeginnDreharbeiten", "displayName": "Beginn der Dreharbeiten" },
      { "type": "number", "name": "LaengeInMin", "displayName": "Länge in Minuten" },
      { "type": "text", "name": "Filmtyp", "displayName": "Typ / Genre", "options": ["Reisedokumentation", "TV-Dokumentation", "Dokumentation", "Kurzdokumentation", "Experimentell", "TV-Spielfilm", "Serie"]},
      { "type": "text", "name": "Kommentar", "displayName": "Kommentar" },
      { "type": "date", "name": "Erstausstrahlung", "displayName": "Erstausstrahlung" },
      { "type": "boolean", "name": "AvailableAsDVD", "displayName": "Als DVD erhältlich" },
      { "type": "boolean", "name": "AvailableAsBlueray", "displayName": "Als Blueray erhältlich" },
      { "type": "date", "name": "ReleaseDVD", "displayName": "Erscheinungsdatum DVD" },
      { "type": "date", "name": "ReleaseBlueray", "displayName": "Erscheinungsdatum Blueray" },
      { "type": "number", "name": "Budget", "displayName": "Budget in €" },
      { "type": "number", "name": "AnzahlATEWADMomente", "displayName": "Anzal der ATEWAD Momente" },
      { "type": "number", "name": "ScoreATEWAD", "displayName": "ATEWAD-Score" }
    ],
    "infoQueries": [
      {
        "name": "Alle Filme vom selben Regisseur",
        "query": {
          "select": [["f.name", "Film"], ["f.jahr", "Jahr"]],
          "from": "film f",
          "where": ["f.regie = {regie}"],
          "oder": ["f.jahr ASC"]
        }
      }
    ]
  }
